### ISSUE TITLE
Manage a Situation Where Assets Are Stored in Multiple Storage Accounts

### ISSUE THREAD

**Issue by melindawangmsft** [Azure/azure-media-migration#103] opened 2023-08-01 23:11 UTC
Handle the situation when ams account has multiple storage accounts, and the asset is not in the primary storage account. 
update the following code looping through all containers
 if (!await container.ExistsAsync(cancellationToken))
                {
                     ...
                    return false;
                }

**Comment by duggaraju** [comment] 2023-08-09 03:35
Duplicate of #101

**Closed** 2023-08-09 03:36 UTC
